#' @keywords internal
#' @aliases joker-package
"_PACKAGE"

## usethis namespace: start
#' @importFrom grDevices dev.off
#' @importFrom grDevices pdf
#' @importFrom methods is
#' @importFrom methods new
#' @importFrom methods slot
#' @importFrom methods slot<-
#' @importFrom methods slotNames
#' @importFrom stats cov
#' @importFrom stats dbeta
#' @importFrom stats dbinom
#' @importFrom stats dcauchy
#' @importFrom stats dchisq
#' @importFrom stats dexp
#' @importFrom stats df
#' @importFrom stats dgamma
#' @importFrom stats dgeom
#' @importFrom stats dlnorm
#' @importFrom stats dmultinom
#' @importFrom stats dnbinom
#' @importFrom stats dnorm
#' @importFrom stats dpois
#' @importFrom stats dt
#' @importFrom stats dunif
#' @importFrom stats dweibull
#' @importFrom stats optim
#' @importFrom stats pbeta
#' @importFrom stats pbinom
#' @importFrom stats pcauchy
#' @importFrom stats pchisq
#' @importFrom stats pexp
#' @importFrom stats pf
#' @importFrom stats pgamma
#' @importFrom stats pgeom
#' @importFrom stats plnorm
#' @importFrom stats pnbinom
#' @importFrom stats pnorm
#' @importFrom stats ppois
#' @importFrom stats pt
#' @importFrom stats punif
#' @importFrom stats pweibull
#' @importFrom stats qbeta
#' @importFrom stats qbinom
#' @importFrom stats qcauchy
#' @importFrom stats qchisq
#' @importFrom stats qexp
#' @importFrom stats qf
#' @importFrom stats qgamma
#' @importFrom stats qgeom
#' @importFrom stats qlnorm
#' @importFrom stats qnbinom
#' @importFrom stats qnorm
#' @importFrom stats qpois
#' @importFrom stats qt
#' @importFrom stats qunif
#' @importFrom stats qweibull
#' @importFrom stats rbeta
#' @importFrom stats rbinom
#' @importFrom stats rcauchy
#' @importFrom stats rchisq
#' @importFrom stats rexp
#' @importFrom stats rf
#' @importFrom stats rgamma
#' @importFrom stats rgeom
#' @importFrom stats rlnorm
#' @importFrom stats rmultinom
#' @importFrom stats rnbinom
#' @importFrom stats rnorm
#' @importFrom stats rpois
#' @importFrom stats rt
#' @importFrom stats runif
#' @importFrom stats rweibull
#' @importFrom stats sd
#' @importFrom stats var
#' @importFrom utils methods
## usethis namespace: end
NULL
